name: telegram message
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: ${{ github.actor }} created a ${{ github.event_name }} with ${{ github.head_ref }}.
